### PR TITLE
Add support for Python 3.7

### LINKED ISSUE #67: Add support for Python 3.7
Python 3.6 is old and busted, python 3.7 is new hotness

### PR DESCRIPTION
**Pull request by hugovk**
Includes #68.

Resolves #67.

Python 3.7 requires Xenial on Travis CI.

### CODE REVIEW

**Comment by bwhmather** [comment]
Broken by changes in #69.  Rebase and will enthusiastically rubber stamp.

**Comment by bwhmather** [comment]
Maybe I shouldn't say anything.  You seem to have got this...

**Comment by hugovk** [comment]
Rebased! 

There's a lint error for Python 3.7, but otherwise the tests pass:

```
3.94s$ pylint -E validation setup.py
************* Module validation.string
validation/string.py:10:20: E1101: Module 're' has no '_pattern_type' member (no-member)
The command "pylint -E validation setup.py" exited with 2.
```

How should it be handled? It's from this import:

```python
# The typing module provides an abstract base class that we can check compiled
# regular expressions against.  Unfortunately this wasn't available until
# python 3.5.  For older versions of python, we fall back to using the private
# ``_pattern_type`` class in ``re``.
try:
    from typing.re import Pattern as _pattern_type
except ImportError:  # pragma: no cover
    _pattern_type = re._pattern_type
```

**Comment by bwhmather** [comment]
I think we can safely `# pylint: disable=no-member here`.  The `re._pattern_type` line will never be run on versions that don't have it.

**Comment by bwhmather** [comment]
Thanks.  Have merged #70.  Could you rebase this one to keep everything nice and linear.

**Comment by hugovk** [comment]
Sure, will do later today when I'm back at a computer.

**Comment by hugovk** [comment]
Rebased!

**Comment by bwhmather** [comment]
Thank you very much.  Merging

**Pull request merged**
